{% set name = "libmbd" %}
{% set version = "0.15.0" %}
{% set build = 1 %}
{% set mpi = mpi or "nompi" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libmbd/libmbd/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: f309447547f5203c179a9c8344dbf55fd4781852d9e7f248b1c6b5da69e533c8

{% if mpi == "nompi" %}
{% set build = build + 100 %}
{% endif %}
build:
  number: {{ build }}
  skip: true  # [win]

  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  {% if mpi != "nompi" %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
    - {{ stdlib("c") }}    # [osx]
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    # OpenMPI-framework is not found otherwise when cross compiling for osx_arm64
    - {{ mpi }}  # [mpi == "openmpi" and (osx and arm64)]
  host:
    - {{ mpi }}  # [mpi != "nompi"]
    - scalapack  # [mpi != "nompi"]
    # ELSI is (currently) not available for osx_arm64
    - elsi  # [mpi != "nompi" and not (osx and arm64)]
    - libblas
    - liblapack
  run:
    - {{ mpi }}  # [mpi != "nompi"]
    - scalapack  # [mpi != "nompi"]
    # ELSI is (currently) not available for osx_arm64
    - elsi  # [mpi != "nompi" and not (osx and arm64)]

test:
  commands:
    - test -f $PREFIX/lib/libmbd${SHLIB_EXT}

about:
  home: https://github.com/libmbd/{{ name }}
  license: MPL-2.0
  license_file:
    - LICENSE
  summary: Many-body dispersion library
  doc_url: https://libmbd.github.io

extra:
  recipe-maintainers:
    - awvwgk
    - jhrmnn
